# --- General Settings ---
set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1

# --- Keybindings ---
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf \; display "Reloaded tmux config!"

# Unbind Right-Click to allow for normal terminal paste behavior
unbind-key -T root MouseDown3Pane

# --- Plugins ---
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Configure the theme
set -g @catppuccin_flavour 'macchiato'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'